# creating series

In [214]:
import pandas as pd 
import numpy as np

In [216]:
labels = ['a','b','c']
l = [13,12,45]
arr = np.array([11,45,67])
d1 = {1:13,2:45,3:67}
d2 = {'a':13,'b':45,'c':67}

In [217]:
pd.Series(l)

0    13
1    12
2    45
dtype: int64

In [218]:
# pd.Series(my_list, index = labels)
pd.Series(arr, index = labels)

a    11
b    45
c    67
dtype: int64

In [219]:
pd.Series(arr)

0    11
1    45
2    67
dtype: int64

create custom labels

In [220]:
pd.Series(l)

0    13
1    12
2    45
dtype: int64

In [221]:
pd.Series(l,index = arr)

11    13
45    12
67    45
dtype: int64

In [222]:
pd.Series(d)

a    13
b    45
c    67
dtype: int64

Dataframes

# Dataframe

In [223]:
data = {
        'Name' :  ['Stokes', 'Anna' , 'peter','Linda' ],
        'Age':    [28,34,29,40],
        'city':   ['Rampur' ,'Lucknow' , 'delhi', "Berlin"],
        'Salary': [23000 ,25000 , 23000,34000] ,
}  
data
pd.DataFrame(data)

     Name  Age     city  Salary
0  Stokes   28   Rampur   23000
1    Anna   34  Lucknow   25000
2   peter   29    delhi   23000
3   Linda   40   Berlin   34000

In [224]:
data_list = [
        ['Stokes', 30, 'New York',125000 ],
        ['Anna', 40, 'Paris',121000 ],
        ['Peter', 23, 'London', 25000 ],
        ['Linda', 45, 'denmark',140000 ],
       
]

pd.DataFrame(data_list)
col = ['name', 'age','city','salary']
df = pd.DataFrame(data_list, columns=col)
df

     name  age      city  salary
0  Stokes   30  New York  125000
1    Anna   40     Paris  121000
2   Peter   23    London   25000
3   Linda   45   denmark  140000

In [213]:
df[["name",'age']] 
# df["age"]

     name  age
0  Stokes   30
1    Anna   40
2   Peter   23
3   Linda   45

In [142]:
df

     name  age      city  salary
0  Stokes   30  New York  125000
1    Anna   40     Paris  121000
2   Peter   23    London   25000
3   Linda   45   denmark  140000

# inseting a new columns

In [144]:
df["Department"] = ['Doctor','Eng.','Doctor','Eng.'] 
# df['Position'] = ['HR','Manager','Analyst','HR']
df

     name  age      city  salary Department
0  Stokes   30  New York  125000     Doctor
1    Anna   40     Paris  121000       Eng.
2   Peter   23    London   25000     Doctor
3   Linda   45   denmark  140000       Eng.

In [151]:
#drop Department column-- 
df.drop('Department', axis = 1,inplace= True )

In [150]:
df

     name  age      city  salary
0  Stokes   30  New York  125000
1    Anna   40     Paris  121000
2   Peter   23    London   25000
3   Linda   45   denmark  140000

# Slicing (column wise)

In [164]:
# df.loc[[0,1]]
df.loc[[0,1]][['name','city']]

     name      city
0  Stokes  New York
1    Anna     Paris

In [165]:
df[df['age']>=30]

     name  age      city  salary
0  Stokes   30  New York  125000
1    Anna   40     Paris  121000
3   Linda   45   denmark  140000

In [166]:
df[(df['city']=='Paris') & (df['age']==40)]

   name  age   city  salary
1  Anna   40  Paris  121000

In [167]:
df[(df['name']=='Stokes') & (df['city']=='New York')]

     name  age      city  salary
0  Stokes   30  New York  125000

# Find the missing data

In [168]:
data= {
   'A':[1,2,np.nan , 4,5], 
   'B':[2, 5,6,9,10],
   'C': [5,8,np.nan, 10,23],
   'D':[np.nan,6,9,np.nan,np.nan] ,
}
df = pd.DataFrame(data)
df

     A   B     C    D
0  1.0   2   5.0  NaN
1  2.0   5   8.0  6.0
2  NaN   6   NaN  9.0
3  4.0   9  10.0  NaN
4  5.0  10  23.0  NaN

In [169]:
df.isna()

       A      B      C      D
0  False  False  False   True
1  False  False  False  False
2   True  False   True  False
3  False  False  False   True
4  False  False  False   True

In [170]:
df.isna().sum()

A    1
B    0
C    1
D    3
dtype: int64

In [171]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

# Drop and identifiying mising values

In [172]:
df

     A   B     C    D
0  1.0   2   5.0  NaN
1  2.0   5   8.0  6.0
2  NaN   6   NaN  9.0
3  4.0   9  10.0  NaN
4  5.0  10  23.0  NaN

In [173]:
df.dropna()

     A  B    C    D
1  2.0  5  8.0  6.0

In [174]:
df.dropna(thresh=2)

     A   B     C    D
0  1.0   2   5.0  NaN
1  2.0   5   8.0  6.0
2  NaN   6   NaN  9.0
3  4.0   9  10.0  NaN
4  5.0  10  23.0  NaN

# Filling missing values

In [175]:
val = {'A' :100  , 'C':300, 'D':400} 
df.fillna(val)

       A   B      C      D
0    1.0   2    5.0  400.0
1    2.0   5    8.0    6.0
2  100.0   6  300.0    9.0
3    4.0   9   10.0  400.0
4    5.0  10   23.0  400.0

In [176]:
df.fillna(df.sum())

      A   B     C     D
0   1.0   2   5.0  15.0
1   2.0   5   8.0   6.0
2  12.0   6  46.0   9.0
3   4.0   9  10.0  15.0
4   5.0  10  23.0  15.0

In [177]:
df.fillna(df.mean())

     A   B     C    D
0  1.0   2   5.0  7.5
1  2.0   5   8.0  6.0
2  3.0   6  11.5  9.0
3  4.0   9  10.0  7.5
4  5.0  10  23.0  7.5

# Merging and joining

In [178]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
}) 

salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [179]:
pd.merge(salaries, employees)
pd.merge(employees , salaries, on='employee_id' , how = 'inner')
pd.merge(employees , salaries, on='employee_id' , how = 'outer')
pd.merge(employees , salaries, on='employee_id' , how = 'left')
pd.merge(employees , salaries, on='employee_id' , how = 'right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

# Concatinaions of 2 dataframes

In [180]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [181]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [182]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [183]:
pd.concat([df2,df1])

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [184]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

# Join 2 dataframes

In [185]:
df1 = pd.DataFrame({'name': ['Alice', 'Bob', 'Charlie']}, index=[1, 2, 3])

df2 = pd.DataFrame({'score': [85, 90, 75]}, index=[2, 3, 4])

In [186]:
df2

   score
2     85
3     90
4     75

In [187]:
df1.join(df2,how = 'outer') 
df1.join(df2,how = 'inner') 
df1.join(df2,how = 'left')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

# GroupBy

In [188]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}

data
df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [189]:
#calculate the total sales by category  
df.groupby('Category')['Sales'].sum()
#calculate the total sales by store 
df.groupby('Store')['Sales'].sum()

Store
S1    720
S2    780
Name: Sales, dtype: int64

# Aggregations

In [190]:
df['Sales'].mean()
df['Sales'].median()
df['Quantity'].min() 
df['Quantity'].std() 
df['Quantity'].var()

np.float64(30.839285714285715)

In [191]:
df['Sales'].agg(['mean' , 'median' ,'min', 'max', 'std' , 'var'])

mean       187.500000
median     190.000000
min        100.000000
max        300.000000
std         66.062741
var       4364.285714
Name: Sales, dtype: float64

# Pivot tables

In [192]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    315     41   John  January      Q1
1  2023-01-02       B   West    178     48   Mary  January      Q1
2  2023-01-03       C  North    782     98    Bob  January      Q1
3  2023-01-04       D  South    417     22  Alice  January      Q1
4  2023-01-05       A   East    980     94   John  January      Q1
5  2023-01-06       B   West    439     87   Mary  January      Q1
6  2023-01-07       C  North    222     29    Bob  January      Q1
7  2023-01-08       D  South    689     79  Alice  January      Q1
8  2023-01-09       A   East    554     70   John  January      Q1
9  2023-01-10       B   West    403     84   Mary  January      Q1
10 2023-01-11       C  North    767     99    Bob  January      Q1
11 2023-01-12       D  South    811     49  Alice  January      Q1
12 2023-01-13       A   East    164     73   John  January      Q1
13 2023-01-14       B   West    285     56   Mary  January      Q1
14 2023-01-15       C  North    673     25    Bob  January      Q1
15 2023-01-16       D  South    124     98  Alice  January      Q1
16 2023-01-17       A   East    750     34   John  January      Q1
17 2023-01-18       B   West    445     35   Mary  January      Q1
18 2023-01-19       C  North    747     73    Bob  January      Q1
19 2023-01-20       D  South    945     41  Alice  January      Q1

In [193]:
pd.pivot_table(df,values= ['Sales','Units'], index = 'Region', columns= 'Product')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     552.6    NaN    NaN    NaN  62.4   NaN   NaN   NaN
North      NaN    NaN  638.2    NaN   NaN   NaN  64.8   NaN
South      NaN    NaN    NaN  597.2   NaN   NaN   NaN  57.8
West       NaN  350.0    NaN    NaN   NaN  62.0   NaN   NaN

In [194]:
pd.crosstab(df["Region"], df["Product"])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

# Operations

In [195]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [196]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [197]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [198]:
df1.shape

(5, 3)

In [199]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [200]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [201]:
df1['B']+10

0    20
1    30
2    40
3    50
4    60
Name: B, dtype: int64

In [202]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [203]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [204]:
def square(x):
    return x**2

In [205]:
df1['D'] = df1['B'].apply(square)

In [206]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500